# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_auth_code(object):
    def setupUi(self, Dialog_auth_code):
        Dialog_auth_code.setObjectName("Dialog_auth_code")
        Dialog_auth_code.resize(404, 552)
        Dialog_auth_code.setStyleSheet("background-color: rgb(67, 67, 67);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_auth_code)
        self.pushButton_cancel.setGeometry(QtCore.QRect(20, 430, 351, 91))
        self.pushButton_cancel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label = QtWidgets.QLabel(Dialog_auth_code)
        self.label.setGeometry(QtCore.QRect(10, 20, 371, 191))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 34pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_auth_code = QtWidgets.QLineEdit(Dialog_auth_code)
        self.lineEdit_auth_code.setGeometry(QtCore.QRect(10, 230, 371, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_auth_code.setFont(font)
        self.lineEdit_auth_code.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(157, 157, 157);\n"
"border-radius: 25px;")
        self.lineEdit_auth_code.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_auth_code.setObjectName("lineEdit_auth_code")
        self.pushButton_accept = QtWidgets.QPushButton(Dialog_auth_code)
        self.pushButton_accept.setGeometry(QtCore.QRect(20, 320, 351, 91))
        self.pushButton_accept.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_accept.setObjectName("pushButton_accept")

        self.retranslateUi(Dialog_auth_code)
        QtCore.QMetaObject.connectSlotsByName(Dialog_auth_code)

    def retranslateUi(self, Dialog_auth_code):
        _translate = QtCore.QCoreApplication.translate
        Dialog_auth_code.setWindowTitle(_translate("Dialog_auth_code", "Dialog"))
        self.pushButton_cancel.setText(_translate("Dialog_auth_code", "ОТМЕНА"))
        self.label.setText(_translate("Dialog_auth_code", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:792;\">Введите код</span></p><p><span style=\" font-size:36pt; font-weight:792;\">аутентификации</span></p></body></html>"))
        self.lineEdit_auth_code.setPlaceholderText(_translate("Dialog_auth_code", "Код аутентификации.."))
        self.pushButton_accept.setText(_translate("Dialog_auth_code", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_auth_code = QtWidgets.QDialog()
    ui = Ui_Dialog_auth_code()
    ui.setupUi(Dialog_auth_code)
    Dialog_auth_code.show()
    sys.exit(app.exec_())
