# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lockscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lockscreen_window(object):
    def setupUi(self, lockscreen_window):
        lockscreen_window.setObjectName("lockscreen_window")
        lockscreen_window.resize(404, 822)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../AppData/Local/Android_app/icons/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        lockscreen_window.setWindowIcon(icon)
        lockscreen_window.setStyleSheet("background-color: rgb(67, 67, 67);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(lockscreen_window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_enter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enter.setGeometry(QtCore.QRect(30, 430, 351, 91))
        self.pushButton_enter.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.lineEdit_pin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pin.setGeometry(QtCore.QRect(20, 340, 371, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_pin.setFont(font)
        self.lineEdit_pin.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(157, 157, 157);\n"
"border-radius: 25px;")
        self.lineEdit_pin.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pin.setObjectName("lineEdit_pin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 371, 211))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 34pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(30, 620, 351, 91))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        lockscreen_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(lockscreen_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 26))
        self.menubar.setObjectName("menubar")
        lockscreen_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(lockscreen_window)
        self.statusbar.setObjectName("statusbar")
        lockscreen_window.setStatusBar(self.statusbar)

        self.retranslateUi(lockscreen_window)
        QtCore.QMetaObject.connectSlotsByName(lockscreen_window)

    def retranslateUi(self, lockscreen_window):
        _translate = QtCore.QCoreApplication.translate
        lockscreen_window.setWindowTitle(_translate("lockscreen_window", "Тестовый Проект"))
        self.pushButton_enter.setText(_translate("lockscreen_window", "ОК"))
        self.lineEdit_pin.setPlaceholderText(_translate("lockscreen_window", "Введите пароль"))
        self.label.setText(_translate("lockscreen_window", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:792;\">VkPASS CHANGER</span></p><p><span style=\" font-weight:600;\">LOCKED. </span></p><p><span style=\" font-weight:600;\">ENTER PASSWORD:</span></p></body></html>"))
        self.pushButton_exit.setText(_translate("lockscreen_window", "ВЫХОД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    lockscreen_window = QtWidgets.QMainWindow()
    ui = Ui_lockscreen_window()
    ui.setupUi(lockscreen_window)
    lockscreen_window.show()
    sys.exit(app.exec_())
