# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(404, 822)
        MainWindow.setMaximumSize(QtCore.QSize(408, 831))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/icons/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(67, 67, 67);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_update_password = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update_password.setGeometry(QtCore.QRect(30, 430, 351, 91))
        self.pushButton_update_password.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_update_password.setObjectName("pushButton_update_password")
        self.lineEdit_new_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_new_password.setGeometry(QtCore.QRect(20, 280, 371, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_new_password.setFont(font)
        self.lineEdit_new_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(157, 157, 157);\n"
"border-radius: 25px;")
        self.lineEdit_new_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_new_password.setObjectName("lineEdit_new_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 371, 191))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 34pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_settings.setGeometry(QtCore.QRect(30, 550, 351, 91))
        self.pushButton_settings.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(30, 670, 351, 91))
        self.pushButton_exit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тестовый Проект"))
        self.pushButton_update_password.setText(_translate("MainWindow", "ОБНОВИТЬ ПАРОЛЬ"))
        self.lineEdit_new_password.setPlaceholderText(_translate("MainWindow", "Здесь будет ваш новый пароль"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:800;\">VkPASS CHANGER</span></p><p><span style=\" font-size:36pt; font-weight:800;\">created by ILYXAAA</span></p></body></html>"))
        self.pushButton_settings.setText(_translate("MainWindow", "НАСТРОЙКИ"))
        self.pushButton_exit.setText(_translate("MainWindow", "ВЫХОД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
