# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(408, 831)
        settings_window.setMinimumSize(QtCore.QSize(408, 831))
        settings_window.setMaximumSize(QtCore.QSize(408, 831))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../AppData/Local/Android_app/icons/window_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settings_window.setWindowIcon(icon)
        settings_window.setStyleSheet("background-color: rgb(67, 67, 67);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(settings_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 371, 90))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("font: 24pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_yes = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yes.setGeometry(QtCore.QRect(20, 110, 161, 61))
        self.pushButton_yes.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_yes.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 20px;\n"
"    \n"
"}")
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.pushButton_no = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_no.setGeometry(QtCore.QRect(220, 110, 171, 61))
        self.pushButton_no.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_no.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 20px;\n"
"    \n"
"}")
        self.pushButton_no.setObjectName("pushButton_no")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 371, 51))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 24pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_vk_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_vk_password.setGeometry(QtCore.QRect(20, 290, 371, 71))
        self.lineEdit_vk_password.setMinimumSize(QtCore.QSize(371, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_vk_password.setFont(font)
        self.lineEdit_vk_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(157, 157, 157);\n"
"border-radius: 25px;")
        self.lineEdit_vk_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_vk_password.setObjectName("lineEdit_vk_password")
        self.pushButton_show_password = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show_password.setGeometry(QtCore.QRect(240, 380, 151, 71))
        self.pushButton_show_password.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_show_password.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_show_password.setObjectName("pushButton_show_password")
        self.pushButton_clear_password = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_password.setGeometry(QtCore.QRect(20, 380, 211, 71))
        self.pushButton_clear_password.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_clear_password.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_clear_password.setObjectName("pushButton_clear_password")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 500, 371, 51))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("font: 24pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_set_vk_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_set_vk_password.setGeometry(QtCore.QRect(20, 560, 371, 71))
        self.lineEdit_set_vk_password.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_set_vk_password.setFont(font)
        self.lineEdit_set_vk_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(157, 157, 157);\n"
"border-radius: 25px;")
        self.lineEdit_set_vk_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_set_vk_password.setObjectName("lineEdit_set_vk_password")
        self.pushButton_set_password = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_password.setGeometry(QtCore.QRect(20, 650, 371, 61))
        self.pushButton_set_password.setMinimumSize(QtCore.QSize(171, 61))
        self.pushButton_set_password.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 20pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_set_password.setObjectName("pushButton_set_password")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(20, 720, 371, 61))
        self.pushButton_back.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_back.setStyleSheet("QPushButton{\n"
"    background-color: rgb(52, 178, 151);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 112, 112);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 30pt \"Impact\";\n"
"    border-radius: 30px;\n"
"    \n"
"}")
        self.pushButton_back.setObjectName("pushButton_back")
        settings_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(settings_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 408, 26))
        self.menubar.setObjectName("menubar")
        settings_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(settings_window)
        self.statusbar.setObjectName("statusbar")
        settings_window.setStatusBar(self.statusbar)

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Тестовый Проект"))
        self.label.setText(_translate("settings_window", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">Двухфакторная</span></p><p><span style=\" font-size:28pt; font-weight:600;\">аутентификация:</span></p></body></html>"))
        self.pushButton_yes.setText(_translate("settings_window", "Да"))
        self.pushButton_no.setText(_translate("settings_window", "Нет"))
        self.label_2.setText(_translate("settings_window", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">Посмотреть пароль от ВК:</span></p></body></html>"))
        self.lineEdit_vk_password.setPlaceholderText(_translate("settings_window", "Тут будет пароль от вк.."))
        self.pushButton_show_password.setText(_translate("settings_window", "Посмотреть"))
        self.pushButton_clear_password.setText(_translate("settings_window", "Стереть пароль"))
        self.label_3.setText(_translate("settings_window", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">Задать пароль от ВК:</span></p></body></html>"))
        self.lineEdit_set_vk_password.setPlaceholderText(_translate("settings_window", "Введите пароль.."))
        self.pushButton_set_password.setText(_translate("settings_window", "Подтвердить"))
        self.pushButton_back.setText(_translate("settings_window", "НАЗАД"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings_window = QtWidgets.QMainWindow()
    ui = Ui_settings_window()
    ui.setupUi(settings_window)
    settings_window.show()
    sys.exit(app.exec_())
